from collections.abc import Iterable

from hypothesis import given, settings
from hypothesis import strategies as st

from sash.symbolic.strings import SymStr
from sash.util import create_fresh_varname

settings.register_profile("default", max_examples=5)
settings.load_profile("default")

@given(l=st.lists(st.text()))
def test_symbstr_to_str_with_strings(l: list[str]) -> None:
    """Property-based test for `symbstr_to_str` with only string components."""
    symbstr = SymStr(tuple(l))

    # If all components are strings, the result should be their concatenation.
    assert symbstr.try_to_str() == "".join(l)


def test_symbstr_to_str_empty_iterable() -> None:
    """Property-based test `symbstr_to_str` with an empty iterable."""
    symbstr: Iterable[str] = []

    # The result should be an empty string.
    assert SymStr(tuple(symbstr)).try_to_str() == ""


z3_prefixes = st.one_of(
    st.just(None), st.just(""), st.from_regex(r"[A-Za-z_][A-Za-z0-9_]*", fullmatch=True)
)


def test_create_fresh_varname_default_prefix() -> None:
    """Test for `create_fresh_varname` with the default prefix."""
    name = create_fresh_varname()

    # The generated name should start with "vr".
    assert name.startswith("vr")

    # The generated name should be at least as long as "vr".
    assert len(name) >= len("vr")


@given(prefix=z3_prefixes)
def test_create_fresh_varname_with_prefix(prefix: str | None) -> None:
    """Property-based test for `create_fresh_varname` with any prefix."""
    name = create_fresh_varname(prefix)
    expected_prefix = "vr" if prefix is None else prefix

    # The generated name should start with the expected prefix.
    assert name.startswith(expected_prefix)

    # The generated name should be at least as long as the expected prefix.
    assert len(name) >= len(expected_prefix)


@given(prefix=z3_prefixes, n=st.integers(min_value=1, max_value=100))
def test_create_fresh_varname_is_unique(prefix: str | None, n: int) -> None:
    """Property-based test for uniqueness of the names generated by `create_fresh_varname`."""
    names = [create_fresh_varname(prefix) for _ in range(n)]

    # All generated names should be unique.
    assert len(set(names)) == len(names)


@given(prefix=z3_prefixes)
def test_create_fresh_var_shape_and_uniqueness(prefix: str | None) -> None:
    """Property-based test for the shape and uniqueness of varnames created by `create_fresh_varname`."""
    v1 = create_fresh_varname(prefix)
    v2 = create_fresh_varname(prefix)
    expected_prefix = "vr" if prefix is None else prefix

    # Both variable names should start with the expected prefix.
    assert v1.startswith(expected_prefix)
    assert v2.startswith(expected_prefix)

    # The two created variables should be distinct.
    assert v1 != v2
