name: Run evaluation
on: [push, pull_request]
jobs:
  milestone_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync
      - name: Run the first evaluation milestone
        run: |
          ./scripts/evaluation.sh milestone_1

  milestone_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync
      - name: Run the second evaluation milestone
        run: |
          ./scripts/evaluation.sh milestone_2

  # Add more milestones as needed
